server:
  port: 8080

spring:
  application:
    name: auth-server

  security:
    oauth2:
      authorizationserver:
        issuer: http://authorization-server:8080

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  pattern:
    console: "%d{ISO8601} [%thread] [%-5level] [%X{traceId},%X{spanId}] %logger{36}.%method - %msg %n"
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
